package com.mentorguild.repository.impl;

import com.mentorguild.model.Mentor;
import com.mentorguild.repository.MentorRepository;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import org.springframework.stereotype.Repository;

@Repository
public class InMemoryMentorRepository implements MentorRepository {
  private final Map<UUID, Mentor> store = new ConcurrentHashMap<>();

  @Override
  // Save a mentor and return a generated ID.
  // TODO: Future create database connection so ID is generated by database
  public UUID save(Mentor mentor) {
    UUID id = UUID.randomUUID();
    store.put(id, mentor);
    return id;
  }

  @Override
  // Find a Mentor by ID. (Returns Optional.empty() if not found).
  public Optional<Mentor> findById(UUID id) {
    return Optional.ofNullable(store.get(id));
  }

  @Override
  public List<Mentor> findAll() {
    return new ArrayList<>(store.values());
  }
}
